// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/environs (interfaces: InstanceBroker)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination mocks/environs_mock.go github.com/juju/juju/environs InstanceBroker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	instance "github.com/juju/juju/core/instance"
	environs "github.com/juju/juju/environs"
	instances "github.com/juju/juju/environs/instances"
	gomock "go.uber.org/mock/gomock"
)

// MockInstanceBroker is a mock of InstanceBroker interface.
type MockInstanceBroker struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceBrokerMockRecorder
}

// MockInstanceBrokerMockRecorder is the mock recorder for MockInstanceBroker.
type MockInstanceBrokerMockRecorder struct {
	mock *MockInstanceBroker
}

// NewMockInstanceBroker creates a new mock instance.
func NewMockInstanceBroker(ctrl *gomock.Controller) *MockInstanceBroker {
	mock := &MockInstanceBroker{ctrl: ctrl}
	mock.recorder = &MockInstanceBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanceBroker) EXPECT() *MockInstanceBrokerMockRecorder {
	return m.recorder
}

// AllInstances mocks base method.
func (m *MockInstanceBroker) AllInstances(arg0 context.Context) ([]instances.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllInstances", arg0)
	ret0, _ := ret[0].([]instances.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllInstances indicates an expected call of AllInstances.
func (mr *MockInstanceBrokerMockRecorder) AllInstances(arg0 any) *MockInstanceBrokerAllInstancesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllInstances", reflect.TypeOf((*MockInstanceBroker)(nil).AllInstances), arg0)
	return &MockInstanceBrokerAllInstancesCall{Call: call}
}

// MockInstanceBrokerAllInstancesCall wrap *gomock.Call
type MockInstanceBrokerAllInstancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInstanceBrokerAllInstancesCall) Return(arg0 []instances.Instance, arg1 error) *MockInstanceBrokerAllInstancesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInstanceBrokerAllInstancesCall) Do(f func(context.Context) ([]instances.Instance, error)) *MockInstanceBrokerAllInstancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInstanceBrokerAllInstancesCall) DoAndReturn(f func(context.Context) ([]instances.Instance, error)) *MockInstanceBrokerAllInstancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AllRunningInstances mocks base method.
func (m *MockInstanceBroker) AllRunningInstances(arg0 context.Context) ([]instances.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllRunningInstances", arg0)
	ret0, _ := ret[0].([]instances.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllRunningInstances indicates an expected call of AllRunningInstances.
func (mr *MockInstanceBrokerMockRecorder) AllRunningInstances(arg0 any) *MockInstanceBrokerAllRunningInstancesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllRunningInstances", reflect.TypeOf((*MockInstanceBroker)(nil).AllRunningInstances), arg0)
	return &MockInstanceBrokerAllRunningInstancesCall{Call: call}
}

// MockInstanceBrokerAllRunningInstancesCall wrap *gomock.Call
type MockInstanceBrokerAllRunningInstancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInstanceBrokerAllRunningInstancesCall) Return(arg0 []instances.Instance, arg1 error) *MockInstanceBrokerAllRunningInstancesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInstanceBrokerAllRunningInstancesCall) Do(f func(context.Context) ([]instances.Instance, error)) *MockInstanceBrokerAllRunningInstancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInstanceBrokerAllRunningInstancesCall) DoAndReturn(f func(context.Context) ([]instances.Instance, error)) *MockInstanceBrokerAllRunningInstancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartInstance mocks base method.
func (m *MockInstanceBroker) StartInstance(arg0 context.Context, arg1 environs.StartInstanceParams) (*environs.StartInstanceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartInstance", arg0, arg1)
	ret0, _ := ret[0].(*environs.StartInstanceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartInstance indicates an expected call of StartInstance.
func (mr *MockInstanceBrokerMockRecorder) StartInstance(arg0, arg1 any) *MockInstanceBrokerStartInstanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartInstance", reflect.TypeOf((*MockInstanceBroker)(nil).StartInstance), arg0, arg1)
	return &MockInstanceBrokerStartInstanceCall{Call: call}
}

// MockInstanceBrokerStartInstanceCall wrap *gomock.Call
type MockInstanceBrokerStartInstanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInstanceBrokerStartInstanceCall) Return(arg0 *environs.StartInstanceResult, arg1 error) *MockInstanceBrokerStartInstanceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInstanceBrokerStartInstanceCall) Do(f func(context.Context, environs.StartInstanceParams) (*environs.StartInstanceResult, error)) *MockInstanceBrokerStartInstanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInstanceBrokerStartInstanceCall) DoAndReturn(f func(context.Context, environs.StartInstanceParams) (*environs.StartInstanceResult, error)) *MockInstanceBrokerStartInstanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopInstances mocks base method.
func (m *MockInstanceBroker) StopInstances(arg0 context.Context, arg1 ...instance.Id) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopInstances", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopInstances indicates an expected call of StopInstances.
func (mr *MockInstanceBrokerMockRecorder) StopInstances(arg0 any, arg1 ...any) *MockInstanceBrokerStopInstancesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopInstances", reflect.TypeOf((*MockInstanceBroker)(nil).StopInstances), varargs...)
	return &MockInstanceBrokerStopInstancesCall{Call: call}
}

// MockInstanceBrokerStopInstancesCall wrap *gomock.Call
type MockInstanceBrokerStopInstancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInstanceBrokerStopInstancesCall) Return(arg0 error) *MockInstanceBrokerStopInstancesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInstanceBrokerStopInstancesCall) Do(f func(context.Context, ...instance.Id) error) *MockInstanceBrokerStopInstancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInstanceBrokerStopInstancesCall) DoAndReturn(f func(context.Context, ...instance.Id) error) *MockInstanceBrokerStopInstancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
